import type { Metadata } from 'next';
import './globals.css';
import { pretendard } from '@/shared/config/fonts/custom-font';

export const metadata: Metadata = {
  title: 'DevTime',
  description: 'Generated by DevTime',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className}`}>{children}</body>
    </html>
  );
}
